import { useEffect, useMemo, useState } from 'react';
import { AlertCircle, ArrowUpDown, CheckCircle2, Clock3, Filter, RefreshCw, Search, ShieldAlert, TrendingUp, X } from 'lucide-react';
import { fetchAllScoredJobs, fetchWeeklyPlan } from '../services/api';

const DEPTS = ['ALL', 'Engineering', 'S&T', 'Traction'];
const LEVELS = ['ALL', 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW'];
const WINDOWS = ['ALL', 'NIGHT', 'DAY', 'ANY'];

const levelClass = (v) => ({
  CRITICAL: 'bg-[#C92A2A]/10 text-[#C92A2A] border-[#C92A2A]/25',
  HIGH: 'bg-[#F08C00]/10 text-[#A76614] border-[#F08C00]/25',
  MEDIUM: 'bg-[#EEF5FC] text-[#315F8D] border-[#C9DCEC]',
  LOW: 'bg-[#EEF2F4] text-[#60748A] border-[#D6DEE6]',
}[v] || 'bg-[#F4F6F8] text-[#52606D] border-[#D6DEE6]');

const scoreClass = (s) => s >= 80 ? 'text-[#C92A2A]' : s >= 60 ? 'text-[#A76614]' : 'text-[#315F8D]';

export default function PriorityRiskPage() {
  const [jobs, setJobs] = useState([]); const [plan, setPlan] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [search, setSearch] = useState(''); const [dept, setDept] = useState('ALL'); const [level, setLevel] = useState('ALL'); const [window, setWindow] = useState('ALL'); const [sort, setSort] = useState('score'); const [selected, setSelected] = useState(null);

  const load = async () => { try { setLoading(true); setError(''); const [j, p] = await Promise.all([fetchAllScoredJobs(), fetchWeeklyPlan()]); setJobs(Array.isArray(j) ? j : j?.jobs || []); setPlan(p || null); } catch (e) { setError(e.message || 'Unable to load priority and risk data.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);

  const scheduled = useMemo(() => new Set((plan?.blocks || plan?.scheduled_blocks || []).flatMap(b => b.job_ids || [])), [plan]);
  const deferred = useMemo(() => new Set(plan?.deferred_jobs || []), [plan]);
  const status = (j) => j.status === 'COMPLETED' ? 'COMPLETED' : scheduled.has(j.job_id) ? 'SCHEDULED' : deferred.has(j.job_id) ? 'DEFERRED' : 'PENDING';

  const rows = useMemo(() => { const q = search.trim().toLowerCase(); return [...jobs].filter(j => dept === 'ALL' || j.department === dept).filter(j => level === 'ALL' || j.criticality_level === level).filter(j => window === 'ALL' || String(j.preferred_time || j.preferred_window || 'ANY').toUpperCase() === window).filter(j => !q || [j.job_id,j.asset_id,j.section_id,j.track_id,j.defect_type].some(v => String(v||'').toLowerCase().includes(q))).sort((a,b) => sort === 'due' ? String(a.due_date||'').localeCompare(String(b.due_date||'')) : sort === 'level' ? (LEVELS.indexOf(a.criticality_level)-LEVELS.indexOf(b.criticality_level)) : Number(b.ai_priority_score||0)-Number(a.ai_priority_score||0)); }, [jobs,search,dept,level,window,sort]);
  const metrics = useMemo(() => ({ critical: jobs.filter(j=>j.criticality_level==='CRITICAL').length, high: jobs.filter(j=>j.criticality_level==='HIGH').length, urgent: jobs.filter(j=>Number(j.ai_priority_score||0)>=80).length, pending: jobs.filter(j=>status(j)==='PENDING').length }), [jobs,scheduled,deferred]);
  const reset = () => { setSearch(''); setDept('ALL'); setLevel('ALL'); setWindow('ALL'); setSort('score'); };

  return <main className="min-h-full bg-[#F4F6F8] p-3.5 font-sans text-[#1F2933]"><div className="mx-auto max-w-[1800px] space-y-3">
    <header className="rounded-md border border-[#D6DEE6] bg-white px-4 py-3 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded bg-[#1E3A5F] text-white"><TrendingUp className="h-5 w-5"/></div><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-lg font-black uppercase tracking-wide text-[#1E3A5F]">Priority & Risk</h1><span className="rounded border border-[#D6DEE6] bg-[#F8FAFC] px-2 py-0.5 text-[9px] font-bold uppercase tracking-wider text-[#52606D]">XGBoost Decision Layer</span></div><p className="mt-1 text-[10px] text-[#718294]">Operational risk ranking from the Unified Job Pool. ML prioritizes work; CP-SAT determines the feasible schedule.</p></div></div><button onClick={load} disabled={loading} className="flex items-center justify-center gap-1.5 rounded bg-[#1E3A5F] px-3 py-2 text-[10px] font-bold text-white"><RefreshCw className={`h-3.5 w-3.5 ${loading?'animate-spin':''}`}/> Refresh Risk</button></div></header>
    {error && <div className="rounded border border-[#C92A2A]/25 bg-[#C92A2A]/5 px-3 py-2 text-[10px] font-semibold text-[#C92A2A]"><AlertCircle className="mr-1 inline h-3.5 w-3.5"/>{error}</div>}
    <section className="grid grid-cols-2 gap-2 lg:grid-cols-4">{[['Critical jobs',metrics.critical,'text-[#C92A2A]',ShieldAlert],['AI ≥ 80',metrics.urgent,'text-[#C92A2A]',TrendingUp],['High criticality',metrics.high,'text-[#A76614]',ArrowUpDown],['Pending action',metrics.pending,'text-[#315F8D]',Clock3]].map(([l,v,c,I])=><div key={l} className="rounded border border-[#D6DEE6] bg-white px-3 py-2.5 shadow-sm"><div className="flex items-center justify-between"><span className="text-[9px] font-bold uppercase tracking-wider text-[#718294]">{l}</span><I className={`h-3.5 w-3.5 ${c}`}/></div><div className={`mt-1 font-mono text-xl font-black ${c}`}>{loading?'—':v}</div></div>)}</section>
    <section className="rounded-md border border-[#D6DEE6] bg-white shadow-sm"><div className="border-b border-[#D6DEE6] bg-[#FAFBFC] p-3"><div className="flex flex-col gap-2 md:flex-row"><div className="flex flex-1 items-center gap-2 rounded border border-[#D6DEE6] bg-white px-2.5 py-2"><Search className="h-4 w-4 text-[#718294]"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search job, asset, section, track or defect" className="min-w-0 flex-1 bg-transparent text-[11px] outline-none"/>{search&&<button onClick={()=>setSearch('')}><X className="h-3.5 w-3.5 text-[#718294]"/></button>}</div><div className="flex flex-wrap items-center gap-2"><Filter className="h-3.5 w-3.5 text-[#718294]"/><Select value={dept} set={setDept} options={DEPTS}/><Select value={level} set={setLevel} options={LEVELS}/><Select value={window} set={setWindow} options={WINDOWS}/><Select value={sort} set={setSort} options={['score','due','level']} labels={['AI score','Due date','Criticality']}/>{(search||dept!=='ALL'||level!=='ALL'||window!=='ALL')&&<button onClick={reset} className="rounded border border-[#D6DEE6] px-2 py-1.5 text-[9px] font-bold text-[#52606D]">Reset</button>}</div></div><div className="flex items-center justify-between px-1 pt-2 text-[9px] text-[#718294]"><span><strong className="text-[#1F2933]">{rows.length}</strong> ranked jobs</span><span>Sorted by {sort==='score'?'AI priority score':sort==='due'?'due date':'criticality'}</span></div></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[1100px] border-collapse text-left text-[10px]"><thead><tr className="border-b border-[#D6DEE6] bg-[#F4F6F8] text-[9px] font-bold uppercase tracking-wider text-[#52606D]"><th className="px-3 py-2.5">Rank</th><th className="px-3 py-2.5">Job</th><th className="px-3 py-2.5">Dept</th><th className="px-3 py-2.5">Criticality</th><th className="px-3 py-2.5">AI Score</th><th className="px-3 py-2.5">Due</th><th className="px-3 py-2.5">Risk Context</th><th className="px-3 py-2.5">Plan Status</th></tr></thead><tbody className="divide-y divide-[#E8EDF1]">{rows.map((j,i)=>{const s=Number(j.ai_priority_score||0);const st=status(j);return <tr key={j.job_id} onClick={()=>setSelected(j)} className="cursor-pointer hover:bg-[#F7F9FB]"><td className="px-3 py-2.5 font-mono font-black text-[#718294]">#{i+1}</td><td className="px-3 py-2.5"><div className="font-mono font-black text-[#1E3A5F]">{j.job_id}</div><div className="text-[8px] text-[#8796A5]">{j.asset_id||'Asset —'} · {j.section_id||'Section —'}</div></td><td className="px-3 py-2.5 font-bold">{j.department||'—'}</td><td className="px-3 py-2.5"><span className={`rounded border px-1.5 py-0.5 text-[8px] font-bold ${levelClass(j.criticality_level)}`}>{j.criticality_level||'MEDIUM'}</span></td><td className="px-3 py-2.5"><div className={`font-mono text-base font-black ${scoreClass(s)}`}>{s.toFixed(1)}</div><div className="mt-1 h-1 w-20 rounded bg-[#E8EDF1]"><div className="h-1 rounded bg-current" style={{width:`${Math.min(100,s)}%`}}/></div></td><td className="px-3 py-2.5 font-mono">{j.due_date||'—'}</td><td className="px-3 py-2.5 text-[9px] text-[#52606D]"><div>{j.defect_type?.replace(/_/g,' ')||'Maintenance'}</div><div className="text-[#8796A5]">{j.preferred_time||j.preferred_window||'ANY'} · {j.estimated_duration_hours||2}h</div></td><td className="px-3 py-2.5"><span className="rounded border border-[#D6DEE6] bg-[#F8FAFC] px-1.5 py-0.5 text-[8px] font-bold text-[#60748A]">{st}</span></td></tr>})}{!loading&&!rows.length&&<tr><td colSpan="8" className="px-3 py-10 text-center text-[10px] font-semibold text-[#718294]">No jobs match the selected risk filters.</td></tr>}</tbody></table></div></section>
    {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-[#10263D]/30 p-4" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><div className="w-full max-w-2xl rounded-lg border border-[#D6DEE6] bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-[#D6DEE6] px-4 py-3"><div><div className="text-[9px] font-bold uppercase tracking-wider text-[#718294]">Priority & Risk Detail</div><h2 className="mt-1 font-mono text-lg font-black text-[#1E3A5F]">{selected.job_id}</h2></div><button onClick={()=>setSelected(null)}><X className="h-5 w-5 text-[#718294]"/></button></div><div className="grid grid-cols-2 gap-px bg-[#D6DEE6] md:grid-cols-3">{[['AI priority',Number(selected.ai_priority_score||0).toFixed(1)],['Criticality',selected.criticality_level||'MEDIUM'],['Department',selected.department||'—'],['Asset',selected.asset_id||'—'],['Section',selected.section_id||'—'],['Due',selected.due_date||'—'],['Maintenance',String(selected.defect_type||'Maintenance').replace(/_/g,' ')],['Duration',`${selected.estimated_duration_hours||2} h`],['Status',status(selected)]].map(([k,v])=><div key={k} className="bg-white px-3 py-2.5"><div className="text-[8px] font-bold uppercase text-[#8796A5]">{k}</div><div className="mt-1 text-[10px] font-bold text-[#1F2933]">{v}</div></div>)}</div><div className="border-t border-[#D6DEE6] px-4 py-3 text-[9px] text-[#52606D]"><CheckCircle2 className="mr-1 inline h-3.5 w-3.5 text-[#2F9E44]"/>Priority score is advisory; final placement remains subject to railway hard constraints and planner approval.</div></div></div>}
  </div></main>;
}
function Select({value,set,options,labels}) { return <select value={value} onChange={e=>set(e.target.value)} className="rounded border border-[#D6DEE6] bg-white px-2 py-1.5 text-[9px] font-semibold text-[#52606D]">{options.map((o,i)=><option key={o} value={o}>{labels?.[i]||o}</option>)}</select>; }
