import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, CloudRain, GitBranch, Loader2, ShieldCheck, SlidersHorizontal, TrainFront, Truck } from 'lucide-react';
import { fetchApprovedWeeklyPlan, fetchWhatIfOptions, simulateWhatIf } from '../services/api';

const LABELS={TRACK_OUTAGE:'Track Outage',SECTION_OUTAGE:'Section Outage',EMERGENCY_BLOCK:'Emergency Block',FREIGHT_SURGE:'Freight Traffic Surge',MONSOON_SLOWDOWN:'Monsoon / Weather Slowdown'};
const pad=v=>String(v).padStart(2,'0');
const defaultStart=()=>{const d=new Date();d.setMinutes(Math.ceil(d.getMinutes()/15)*15,0,0);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;};
const severity={LOW:'border-[#BFD8CB] bg-[#F3F8F5] text-[#176B45]',MODERATE:'border-[#BDD0E1] bg-[#F2F6FA] text-[#285B88]',HIGH:'border-[#E4CA9C] bg-[#FFF8EA] text-[#8A5A10]',CRITICAL:'border-[#E2B9B9] bg-[#FFF4F4] text-[#A51D1D]'};
const Metric=({label,value})=><div className="bg-white px-4 py-3.5"><div className="text-[9px] font-bold uppercase tracking-[.14em] text-[#6C7D8D]">{label}</div><div className="mt-1 text-[22px] font-bold tracking-tight text-[#173E6C]">{value}</div></div>;

export default function WhatIfScenarioPage(){
 const [options,setOptions]=useState({scenario_types:[],sections:[]});const [baseline,setBaseline]=useState(null);const [scenarioType,setScenarioType]=useState('FREIGHT_SURGE');const [sectionId,setSectionId]=useState('');const [trackId,setTrackId]=useState('');const [impactPercent,setImpactPercent]=useState('20');const [startTime,setStartTime]=useState(defaultStart);const [duration,setDuration]=useState(120);const [result,setResult]=useState(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [shell,setShell]=useState(true);
 useEffect(()=>{Promise.all([fetchWhatIfOptions(),fetchApprovedWeeklyPlan()]).then(([o,b])=>{setOptions(o||{scenario_types:[],sections:[]});setBaseline(b);const s=o?.sections?.[0];if(s){setSectionId(s.section_id);setTrackId(s.track_ids?.[0]||'');}}).catch(e=>setError(e.message||'Unable to load scenario inputs.')).finally(()=>setShell(false));},[]);
 const selectedSection=useMemo(()=>options.sections.find(s=>s.section_id===sectionId),[options.sections,sectionId]);const approvedWeek=Number(baseline?.planning_week||baseline?.plan?.planning_week||1);const hasBaseline=Boolean(baseline?.approved&&baseline?.plan);const demand=scenarioType==='FREIGHT_SURGE'||scenarioType==='MONSOON_SLOWDOWN';const meta=scenarioType==='FREIGHT_SURGE'?{icon:Truck,title:'Goods traffic stress',help:'Enter the expected increase in freight demand.'}:{icon:CloudRain,title:'Weather stress',help:'Enter the expected operational slowdown.'};
 const run=async()=>{setError('');setResult(null);const pct=Number(impactPercent);if(!hasBaseline)return setError('An approved weekly baseline is required before running a What-If simulation.');if(demand&&(!Number.isInteger(pct)||pct<1||pct>100))return setError('Enter a whole-number percentage between 1% and 100%.');setLoading(true);try{setResult(await simulateWhatIf({week:approvedWeek,scenario_type:scenarioType,section_id:sectionId,...(scenarioType==='TRACK_OUTAGE'||(!demand&&trackId)?{track_id:trackId}:{}),...(demand?{impact_percent:pct}:{}),start_time:new Date(startTime).toISOString(),duration_minutes:Number(duration)}));}catch(e){setError(e.message||'Scenario simulation failed.');}finally{setLoading(false);}};
 if(shell)return <div className="p-6 text-sm text-[#60748A]">Loading What-If Analysis…</div>;
 return <main className="min-h-full bg-[#F1F4F7] p-4 lg:p-6"><div className="mx-auto max-w-[1220px]">
  <header className="mb-5 flex flex-col gap-3 border-b border-[#CBD5DE] pb-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-1 flex items-center gap-2 text-[9px] font-bold uppercase tracking-[.18em] text-[#63778A]"><SlidersHorizontal className="h-3.5 w-3.5"/> Planner / Scenario Analysis</div><h1 className="text-[25px] font-bold tracking-tight text-[#173E6C]">Operational What-If</h1><p className="mt-1 text-[11px] text-[#607487]">Test operational stress against the approved weekly maintenance plan.</p></div><div className="flex w-fit items-center gap-2 border border-[#C6DCCF] bg-[#F5FAF7] px-3 py-2 text-[9px] font-bold uppercase tracking-[.1em] text-[#176B45]"><ShieldCheck className="h-4 w-4"/> Baseline protected</div></header>
  <div className="grid gap-5 xl:grid-cols-[440px_minmax(0,1fr)]">
   <section className="border border-[#CCD6DF] bg-white"><div className="border-b border-[#DCE3E9] bg-[#F7F9FA] px-5 py-4"><div className="flex items-center gap-2"><GitBranch className="h-4 w-4 text-[#245D91]"/><div><div className="text-[9px] font-bold uppercase tracking-[.14em] text-[#728394]">Scenario setup</div><h2 className="mt-0.5 text-[14px] font-bold text-[#173E6C]">Define the operating condition</h2></div></div></div>
    <div className="space-y-4 p-5"><label className="block"><span className="mb-1.5 block text-[9px] font-bold uppercase tracking-[.13em] text-[#607487]">Scenario type</span><select value={scenarioType} onChange={e=>{setScenarioType(e.target.value);setResult(null);if(e.target.value==='FREIGHT_SURGE')setImpactPercent('20');if(e.target.value==='MONSOON_SLOWDOWN')setImpactPercent('10');}} className="h-10 w-full border border-[#BBC8D3] bg-white px-3 text-[11px] font-semibold text-[#264B6E] outline-none focus:border-[#245D91]">{(options.scenario_types.length?options.scenario_types:Object.keys(LABELS)).map(t=><option key={t} value={t}>{LABELS[t]||t}</option>)}</select></label>
     {demand&&<div className="border border-[#D2DCE4] bg-[#F7F9FA] p-4"><div className="flex items-start gap-3"><div className="flex h-8 w-8 items-center justify-center border border-[#C9D6E0] bg-white text-[#245D91]">{scenarioType==='FREIGHT_SURGE'?<Truck className="h-4 w-4"/>:<CloudRain className="h-4 w-4"/>}</div><div className="flex-1"><div className="text-[10px] font-bold uppercase tracking-[.12em] text-[#355675]">{meta.title}</div><div className="mt-0.5 text-[9px] text-[#718294]">{meta.help}</div></div><div className="font-mono text-[11px] font-bold text-[#245D91]">{impactPercent||0}%</div></div><div className="mt-4 flex items-center gap-3"><input type="range" min="1" max="100" step="1" value={Number(impactPercent)||1} onChange={e=>{setImpactPercent(e.target.value);setResult(null);}} className="h-1.5 flex-1 accent-[#245D91]"/><div className="flex h-9 w-[82px] items-center border border-[#AEBCC8] bg-white px-2"><input aria-label="Scenario percentage" type="number" min="1" max="100" step="1" value={impactPercent} onChange={e=>{setImpactPercent(e.target.value);setResult(null);}} className="w-full text-right text-[12px] font-bold text-[#173E6C] outline-none"/><span className="ml-1 text-[11px] text-[#68798A]">%</span></div></div><div className="mt-2 text-[8px] text-[#7A8997]">Human input · 1–100% · whole numbers</div></div>}
     <label className="block"><span className="mb-1.5 block text-[9px] font-bold uppercase tracking-[.13em] text-[#607487]">Section</span><select value={sectionId} onChange={e=>{setSectionId(e.target.value);const s=options.sections.find(x=>x.section_id===e.target.value);setTrackId(s?.track_ids?.[0]||'');setResult(null);}} className="h-10 w-full border border-[#BBC8D3] bg-white px-3 text-[11px] font-semibold text-[#264B6E] outline-none focus:border-[#245D91]">{options.sections.map(s=><option key={s.section_id} value={s.section_id}>{s.section_id}</option>)}</select></label>
     <label className="block"><span className="mb-1.5 block text-[9px] font-bold uppercase tracking-[.13em] text-[#607487]">Track {scenarioType==='SECTION_OUTAGE'||demand?'(not required)':''}</span><select value={trackId} onChange={e=>{setTrackId(e.target.value);setResult(null);}} disabled={!selectedSection||scenarioType==='SECTION_OUTAGE'||demand} className="h-10 w-full border border-[#BBC8D3] bg-white px-3 text-[11px] font-semibold text-[#264B6E] outline-none disabled:bg-[#F1F4F6] focus:border-[#245D91]">{selectedSection?.track_ids?.map(t=><option key={t} value={t}>{t}</option>)}</select></label>
     <div className="grid grid-cols-2 gap-3"><label><span className="mb-1.5 block text-[9px] font-bold uppercase tracking-[.13em] text-[#607487]">Start time</span><input type="datetime-local" step="900" value={startTime} onChange={e=>{setStartTime(e.target.value);setResult(null);}} className="h-10 w-full border border-[#BBC8D3] bg-white px-3 text-[10px] font-semibold text-[#264B6E] outline-none focus:border-[#245D91]"/></label><label><span className="mb-1.5 block text-[9px] font-bold uppercase tracking-[.13em] text-[#607487]">Duration</span><select value={duration} onChange={e=>{setDuration(e.target.value);setResult(null);}} className="h-10 w-full border border-[#BBC8D3] bg-white px-3 text-[11px] font-semibold text-[#264B6E] outline-none focus:border-[#245D91]"><option value="60">1 hour</option><option value="120">2 hours</option><option value="180">3 hours</option><option value="240">4 hours</option><option value="360">6 hours</option><option value="480">8 hours</option><option value="720">12 hours</option></select></label></div>
     {error&&<div className="flex gap-2 border border-[#E1BABA] bg-[#FFF5F5] p-3 text-[10px] leading-4 text-[#A51D1D]"><AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0"/>{error}</div>}{!hasBaseline&&!error&&<div className="border border-[#E3CA9B] bg-[#FFF9EE] p-3 text-[10px] text-[#8A5A10]">Approve the current weekly plan before running a scenario.</div>}
     <button type="button" disabled={loading||!hasBaseline||!sectionId} onClick={run} className="flex h-11 w-full items-center justify-center gap-2 bg-[#245D91] text-[10px] font-bold uppercase tracking-[.13em] text-white transition hover:bg-[#1D4F7C] disabled:cursor-not-allowed disabled:opacity-50">{loading?<><Loader2 className="h-4 w-4 animate-spin"/> Evaluating Scenario…</>:<><TrainFront className="h-4 w-4"/> Assess Scenario</>}</button>
    </div></section>
   <section className="border border-[#CCD6DF] bg-white"><div className="flex items-center justify-between border-b border-[#DCE3E9] bg-[#F7F9FA] px-5 py-4"><div><div className="text-[9px] font-bold uppercase tracking-[.14em] text-[#728394]">Decision output</div><h2 className="mt-0.5 text-[14px] font-bold text-[#173E6C]">Scenario Assessment</h2></div>{result?.impact?.severity&&<span className={`border px-2.5 py-1 text-[8px] font-bold uppercase tracking-[.12em] ${severity[result.impact.severity]||severity.MODERATE}`}>{result.impact.severity} impact</span>}</div>
    {!result?<div className="flex min-h-[440px] flex-col items-center justify-center px-8 text-center"><div className="flex h-12 w-12 items-center justify-center border border-[#D3DDE5] bg-[#F7F9FA] text-[#728496]"><GitBranch className="h-5 w-5"/></div><h3 className="mt-4 text-[13px] font-bold text-[#355675]">Ready for assessment</h3><p className="mt-1 max-w-[430px] text-[10px] leading-5 text-[#718294]">Run the scenario to compare its operational impact with the approved baseline.</p></div>:<div className="p-5"><div className="grid grid-cols-2 gap-px border border-[#D7DEE6] bg-[#D7DEE6] sm:grid-cols-3"><Metric label="Jobs affected" value={result.impact.jobs_affected}/><Metric label="Jobs moved" value={result.impact.jobs_delayed_or_moved}/><Metric label="Additional deferrals" value={result.impact.additional_deferrals}/><Metric label="Blocks affected" value={result.impact.blocks_affected}/><Metric label="Baseline jobs" value={result.impact.baseline_scheduled_jobs}/><Metric label="Scenario jobs" value={result.impact.scenario_scheduled_jobs}/></div><div className="mt-5 border border-[#D7DEE6]"><div className="border-b border-[#D7DEE6] bg-[#F7F9FA] px-4 py-3 text-[9px] font-bold uppercase tracking-[.13em] text-[#45647F]">Operational consequences</div><div className="space-y-2.5 p-4">{result.operational_impact?.map((x,i)=><div key={`${x}-${i}`} className="flex gap-2 text-[10px] leading-5 text-[#5E7082]"><span className="mt-2 h-1.5 w-1.5 shrink-0 bg-[#6E8296]"/>{x}</div>)}</div></div><div className="mt-4 flex items-center gap-2 border border-[#C7DCCF] bg-[#F5FAF7] px-4 py-3"><CheckCircle2 className="h-4 w-4 text-[#176B45]"/><div><div className="text-[10px] font-bold text-[#236148]">Approved baseline unchanged</div><div className="text-[9px] text-[#628070]">Simulation is non-destructive.</div></div></div></div>}
   </section>
  </div></div></main>;
}
